# Generated by Django 3.1.7 on 2021-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_create_bid_and_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
