# Generated by Django 3.1.7 on 2021-03-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0002_item_name_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name"]},
        ),
    ]
