# Generated by Django 3.1.7 on 2021-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_remove_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
